[package]
name = "pojdectl-rs"
version = "0.1.0"
authors = ["Felicitas Pojtinger <felicitas@pojtinger.com>"]
edition = "2018"
description = "Experimental Rust implementation of https://github.com/pojntfx/pojde's `pojdectl`."
license = "AGPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = "3.0.0-beta.2"
self_update = { version = "0.27.0", features = ["rustls"], default-features = false }
shiplift = "0.7.0"
futures = "0.3.15"
spinners = "1.2.0"
ansi-escapes = "0.1.0"

[dev-dependencies]
cargo-watch = "7.8.0"
