[package]
name = "pojdectl-rs"
version = "0.1.0"
authors = ["Felicitas Pojtinger <felicitas@pojtinger.com>"]
edition = "2018"
description = "Experimental Rust implementation of https://github.com/pojntfx/pojde's `pojdectl`."
license = "AGPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bollard = "0.11.0"
tokio = { version = "1", features = ["full"] }
clap = "3.0.0-beta.2"
maplit = "1.0.2"
openssh = "0.8.0"
tabled = { version = "0.2.1", features = ["color"] }
owo-colors = "2.0.0"

[dev-dependencies]
cargo-watch = "7.8.0"
