[package]
name = "pojdectl-rs"
version = "0.1.0"
authors = ["Felix Pojtinger <felix@pojtinger.com>"]
edition = "2018"
description = "Experimental Rust implementation of https://github.com/pojntfx/pojde's `pojdectl`."
license = "AGPL-3.0"
resolver= "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = "3.0.0-beta.2"
futures = "0.3.15"
spinners = "1.2.0"
ansi-escapes = "0.1.0"
self_update = "0.27.0"
shiplift = "0.7.0"

[target.'cfg(target_os = "windows")'.dependencies]
shiplift = { version = "0.7.0", features = ["vendored-ssl"], default-features = false }

[target.'cfg(target_arch = "riscv64")'.dependencies]
shiplift = { version = "0.7.0", features = ["chrono", "unix-socket", "vendored-ssl"], default-features = false }

[dev-dependencies]
cargo-watch = "7.8.0"
