[package]
name = "pojdectl-rs"
version = "0.1.0"
authors = ["Felix Pojtinger <felix@pojtinger.com>"]
edition = "2018"
description = "Experimental Rust implementation of https://github.com/pojntfx/pojde's `pojdectl`."
license = "AGPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = "3.0.0-beta.2"

[dev-dependencies]
cargo-watch = "7.8.0"
