#!/bin/bash

# Install native dependencies
apt update
apt install -y curl make sudo build-essential gcc-multilib g++-multilib clang llvm "${PKGS}"

# Fix certificate authorities on armv7
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

# Install Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
. /root/.cargo/env

# Set up Rust for cross-compilation
rustup target add "${CARGO_BUILD_TARGET}"
cat <<EOT >/root/.cargo/config
[target.${CARGO_BUILD_TARGET}]
linker = "${CROSS_COMPILER}"
EOT

# Setup up C for cross-compilation
export TARGET_CC=clang

# Install dependencies
USER=root make depend

# Start development or make release
if [ "$1" = 'dev' ]; then
    make dev
else
    make release
fi
