name: hydrun CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - dir: .
            os: debian
            arch: amd64

            cargo_build_target: x86_64-unknown-linux-gnu
            debian_arch: amd64
            debian_pkgs: gcc pkg-config libssl-dev python3 libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev
            macos_pkgs: ""
            linker: x86_64-linux-gnu-gcc
            pkg_config: x86_64-linux-gnu-pkg-config
            target_cc: ""

            bins: [pojdectl-rs, pojdegui-rs]
            suffix: .linux-x86_64

          - dir: .
            os: debian
            arch: amd64

            cargo_build_target: aarch64-unknown-linux-gnu
            debian_arch: arm64
            debian_pkgs: libssl-dev:arm64 python3 libxcb-render0-dev:arm64 libxcb-shape0-dev:arm64 libxcb-xfixes0-dev:arm64 libspeechd-dev:arm64 libxkbcommon-dev:arm64 gcc-aarch64-linux-gnu pkg-config
            macos_pkgs: ""
            linker: aarch64-linux-gnu-gcc
            pkg_config: aarch64-linux-gnu-pkg-config
            target_cc: ""

            bins: [pojdectl-rs, pojdegui-rs]
            suffix: .linux-aarch64

          - dir: .
            os: debian
            arch: amd64

            cargo_build_target: armv7-unknown-linux-gnueabihf
            debian_arch: armhf
            debian_pkgs: libssl-dev:armhf python3 libxcb-render0-dev:armhf libxcb-shape0-dev:armhf libxcb-xfixes0-dev:armhf libspeechd-dev:armhf libxkbcommon-dev:armhf gcc-arm-linux-gnueabihf pkg-config
            macos_pkgs: ""
            linker: arm-linux-gnueabihf-gcc
            pkg_config: arm-linux-gnueabihf-pkg-config
            target_cc: ""

            bins: [pojdectl-rs, pojdegui-rs]
            suffix: .linux-armv7l

          - dir: .
            os: debian
            arch: amd64

            cargo_build_target: riscv64gc-unknown-linux-gnu
            debian_arch: riscv64
            debian_pkgs: gcc-riscv64-linux-gnu # libssl-dev:riscv64 python3 libxcb-render0-dev:riscv64 libxcb-shape0-dev:riscv64 libxcb-xfixes0-dev:riscv64 libspeechd-dev:riscv64 libxkbcommon-dev:riscv64
            linker: riscv64-linux-gnu-gcc
            pkg_config: riscv64-linux-gnu-pkg-config
            target_cc: ""

            bins: [pojdectl-rs, pojdegui-rs]
            suffix: .linux-riscv64

          - dir: .
            os: debian
            arch: amd64

            cargo_build_target: x86_64-pc-windows-gnu
            debian_arch: amd64
            debian_pkgs: llvm clang gcc-mingw-w64 mingw-w64-tools # libssl-dev:amd64
            macos_pkgs: ""
            linker: x86_64-w64-mingw32-gcc
            pkg_config: x86_64-w64-mingw32-pkg-config
            target_cc: clang

            bins: [pojdectl-rs.exe, pojdegui-rs.exe]
            suffix: .windows-x86_64.exe

          - dir: .
            os: joseluisq/rust-linux-darwin-builder
            arch: amd64

            cargo_build_target: x86_64-apple-darwin
            debian_arch: amd64
            debian_pkgs: gcc-multilib g++-multilib
            macos_pkgs: openssl
            linker: x86_64-apple-darwin20.2-clang
            pkg_config: x86_64-apple-darwin20.2-pkg-config
            target_cc: x86_64-apple-darwin20.2-clang

            bins: [pojdectl-rs, pojdegui-rs]
            suffix: .macos-x86_64
          - dir: .
            os: joseluisq/rust-linux-darwin-builder
            arch: amd64

            cargo_build_target: aarch64-apple-darwin
            debian_arch: arm64
            debian_pkgs: ""
            macos_pkgs: openssl
            linker: aarch64-apple-darwin20.2-clang
            pkg_config: aarch64-apple-darwin20.2-pkg-config
            target_cc: aarch64-apple-darwin20.2-clang -arch arm64

            bins: [pojdectl-rs, pojdegui-rs]
            suffix: .macos-aarch64

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up hydrun
        run: |
          curl -L -o /tmp/hydrun https://github.com/pojntfx/hydrun/releases/download/latest/hydrun.linux-$(uname -m)
          sudo install /tmp/hydrun /usr/local/bin
      - name: Build with hydrun
        working-directory: ${{ matrix.project.dir }}
        run: hydrun -o ${{ matrix.project.os }} -a ${{ matrix.project.arch }} 'sh -c "CARGO_BUILD_TARGET=\"${{ matrix.project.cargo_build_target }}\" DEBIAN_ARCH=\"${{ matrix.project.debian_arch }}\" DEBIAN_PKGS=\"${{ matrix.project.debian_pkgs }}\" MACOS_PKGS=\"${{ matrix.project.macos_pkgs }}\" LINKER=\"${{ matrix.project.linker }}\" PKG_CONFIG=\"${{ matrix.project.pkg_config }}\" TARGET_CC=\"${{ matrix.project.target_cc }}\" ./Hydrunfile"'
      - name: Fix permissions for output and copy to temp dir
        working-directory: ${{ matrix.project.dir }}/target/${{ matrix.project.cargo_build_target }}/release
        run: |
          sudo chown -R $USER .
          mkdir -p /tmp/out
          for file in ${{ join(matrix.project.bins,' ') }}; do
            cp $file /tmp/out/$file${{ matrix.project.suffix }}
          done
      - name: Upload output
        uses: actions/upload-artifact@v2
        with:
          name: staging-${{ matrix.project.dir }}
          path: |
            /tmp/out/*

  publish-linux:
    runs-on: ubuntu-latest
    needs: build-linux

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download output
        uses: actions/download-artifact@v2
        with:
          path: /tmp/out
      - name: Publish pre-release to GitHub releases
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: unstable
          prerelease: true
          files: |
            /tmp/out/**/*
      - name: Publish release to GitHub releases
        if: startsWith(github.ref, 'refs/tags/v')
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            /tmp/out/**/*
